version: 2.1
orbs:
    node: circleci/node@5.0.3
jobs:
    release:
        docker:
            - image: circleci/node
        resource_class: small
        steps:
            - node/install:
                node-version: '18.12.1'
            - checkout
            - add_ssh_keys:
                fingerprints:
                    - 'be:9c:81:fc:d9:d0:3f:1f:6c:7c:a1:a8:c7:4a:53:e7'
            - node/install-packages
            - run: npx lerna bootstrap --ci
            - run:
                name: Add Token for NPM Registry
                command: npm config set registry //registry.npmjs.org/:_authToken=$NPM_TOKEN
            - run:
                name: Set Repository User
                command: git config --global user.email $PROJECT_USER_EMAIL && git config --global user.name $PROJECT_USER_NAME
            - run: npx lerna version --no-private --conventional-commits --create-release github --yes

workflows:
    release-packages:
        jobs:
            - release:
                filters:
                    branches:
                        only:
                            - master
