version: 2.1
orbs:
    node: circleci/node@5.0.3

release:
    docker:
        - image: circleci/node
    resource_class: small
    steps:
      - checkout
      - node/with-cache:
          steps:
            - add_ssh_keys:
                fingerprints:
                  - "6e:57:ac:35:af:e6:eb:a8:ca:7b:d2:da:5e:d1:3e:72"
            - run: npx lerna bootstrap --ci
            - run: npx lerna version --no-private --conventional-commits --create-release github --yes
workflows:
  release-packages:
    jobs:
      - release:
          filtters:
            branches:
              only: master
