name: Build and Test

on:
  pull_request:
    types:
      - opened
    branches:
      - 'feat/**'
      - 'features/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build and test
      uses: actions/checkout@v3
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org/
      run: make ci
