name: Build and Test

on:
  pull_request:
    types:
      - opened
    branches:
      - 'feat/**'
      - 'features/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build monorepo and run tests
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: make ci
