name: Release and Publish

on:
    pull_request:
        branches:
        - master
        types: [closed]

permissions:
    contents: write
    packages: write
    pull-requests: write


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build monorepo and run tests
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: make ci
    release:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: Github Identity
              run: |
                git config --global user.name 'github-actions[bot]'
                git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            - uses: actions/checkout@v3
            - name: Create Release
              uses: actions/setup-node@v3
              with:
                node-version: 18
                registry-url: 'https://registry.npmjs.org'
            - run: make ci
            - run: make release
              env:
                NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
