name: Release and Publish

on:
    pull_request:
        branches:
        - master
        types: [closed]

permissions:
    contents: write
    packages: write
    pull-requests: write


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build monorepo and run tests
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: make ci
    release:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0
                persist-credentials: false
            - name: Setup Github Credentials
              run: |
                  git config --global user.name "${{ github.actor }}"
                  git config --global user.email "${{ github.actor }}@users.noreply.github.com"
                  git remote set-url origin https://${{ github.actor }}:${{ secrets.GH_ACCESS_TOKEN }}@github.com/${{ github.repository }}
            - name: Create Release
              uses: actions/setup-node@v3
              with:
                node-version: 18
                registry-url: 'https://registry.npmjs.org'
            - run: make ci
            - run: make release
              env:
                NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
